version: '3.11'

volumes:
    mariadb:

services:
    gateway:
        image: krakenstdio/k-api-gateway:latest
        command: sh -c 'uvicorn main:app --reload --host 0.0.0.0'
        build:
            context: ./gateway
            dockerfile: Dockerfile
        env_file:
            - ./gateway/.env
        ports:
          - 8001:8000
        depends_on:
          - users        
        volumes:
          - ./gateway:/app

    users:
        image: krakenstdio/k-users:latest
        command: sh -c 'uvicorn main:app --reload --host 0.0.0.0'
        build:
            context: ./users
            dockerfile: Dockerfile
        depends_on:
            - db
        env_file:
            - ./users/.env
        volumes:
          - ./users:/app

    db:
        image: mariadb
        restart: always
        ports: 
            - 3307:3306
    
        environment:
            -MYSQL_ROOT_PASSWORD : 'm4st3rcr4ft'
            -MYSQL_DATABASE: 'demo'
            -MYSQL_USER: 'master'
            -MYSQL_PASSWORD: 'craft'

        volumes:
            - mariadb:/var/lib/mysql    
            - ./db/data/initial_script.sql:/docker-entrypoint-initdb.d/initial_script.sql:ro            
