version: '3.7'

volumes:
    mariadb:

services:
    gateway:
        image: krakenstdio/k-api-gateway:latest
        command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
        build:
            context: ./gateway
            dockerfile: Dockerfile
        env_file:
            - ./gateway/.env
        ports:
          - 8001:8000
        depends_on:
          - users
          - orders
        volumes:
          - ./gateway:/app

    users:
        image: krakenstdio/k-users:latest
        command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
        build:
            context: ./users
            dockerfile: Dockerfile
        depends_on:
            - db
        env_file:
            - ./users/.env
        volumes:
          - ./users:/app

    orders:
        image: krakenstdio/k-orders:latest
        command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
        build:
            context: ./orders
            dockerfile: Dockerfile
        env_file:
            - ./orders/.env
        volumes:
          - ./orders:/app
    db:
        image: mariadb
        restart: always
        ports: 
            - 3307:3306
        env_file:
            - ./db/.env
        volumes:
            - mariadb:/var/lib/mysql    
            - ./db/data/initial_script.sql:/docker-entrypoint-initdb.d/initial_script.sql:ro            
